config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config.settings import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('apps.core.urls')),
] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

apps/core/models.py
from datetime import datetime

from django.db import models
# Create your models here.
from django.db.models import ManyToManyField, Sum
from django.contrib.auth.models import User
from django.utils import timezone

from config.settings.base import MEDIA_URL


class Customer(models.Model):
    photo = models.ImageField(upload_to='customers/%d/%m/%Y/', null=True, blank=True)
    name = models.CharField(max_length=25, verbose_name='Nombre')
    date_join = models.DateTimeField(auto_now_add=True, )
    mobile = models.BigIntegerField(null=True, blank=True)

    def to_json(self):
        return {
            'photo': self.photo.url,
            'name': self.name,
            'date_join': self.date_join,
            'mobile': self.mobile,
        }

    def __str__(self):
        return self.name

    def get_photo(self):
        return str(MEDIA_URL) + (str(self.photo))

    def get_utility(self):
        return self.record_set.aggregate(tp=Sum('price'))['tp']

    def get_debts(self):
        return self.record_set.filter(is_debtor=True)

    def get_debt_amount(self):
        debt = 0
        debt = self.record_set.filter(is_debtor=True).aggregate(tp=Sum('price'))['tp']
        return debt

    def get_debt_count(self):
        debt = 0
        debt = self.record_set.filter(is_debtor=True).count()
        return debt

    # daily
    def get_customers_by_current_date(self):
        return self.record_set.filter(record__date_record__day=timezone.now().date().day,
                                      record__date_record__month=timezone.now().date().month,
                                      record__date_record__year=timezone.now().year)


class Record(models.Model):
    price = models.FloatField(verbose_name='Precio')
    is_debtor = models.BooleanField(default=False)
    description = models.TextField(max_length=500, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.RESTRICT)
    date_record = models.DateTimeField(auto_now_add=True, blank=False, null=False)

    def __str__(self):
        return f"Grabación de {self.customer.name} de ${self.price}"


class Message(models.Model):
    receptor = models.ForeignKey(User, on_delete=models.RESTRICT, related_name='receptor_user')
    sender = models.ForeignKey(User, on_delete=models.RESTRICT, related_name='sender_user')
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    class Meta:
        verbose_name = "Mensaje"
        verbose_name_plural = "Mensajes"

    def __str__(self):
        return self.content

apps/core/forms/customer.py
from django.forms import ModelForm, TextInput, FileInput

from apps.core.models import Customer


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre de cliente',
                    'name': 'name',
                    'id': 'customer-name',
                }
            ),
            'mobile': TextInput(
                attrs={
                    'class': 'form-control',
                    'name': 'mobile',
                    'id': 'customer-mobile',
                    'placeholder': 'Por ej: 55555555',
                }
            ),
        }

apps/core/views/customer.py
import json
from datetime import datetime
from typing import Any

from django.contrib import messages
from django.http import JsonResponse, HttpRequest
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, View, DetailView, CreateView, UpdateView, DeleteView

from apps.core.forms.customer import CustomerForm
from apps.core.models import Customer, Record


class CustomerView(View):
    _all = None
    _customer_by_current_day = None

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._all = Customer.objects.all()
        self._customer_by_current_day = Customer.objects.filter(
            record__date_record__day=timezone.now().date().day,
            record__date_record__month=timezone.now().date().month,
            record__date_record__year=timezone.now().year).distinct('name', 'mobile')

    def get_all(self):
        return self._all

    def get_count(self):
        return self._all.count()

    def get_customer_by_current_day(self):
        return self._customer_by_current_day

    def get_customer_by_date_range(self, start_date, end_date):
        if start_date and end_date:
            self._all = self._all = Customer.objects.filter(
                record__date_record__range=(start_date, end_date)).distinct('name', 'mobile')
        if start_date and not end_date:
            self._all = self._all = Customer.objects.filter(
                record__date_record__range=(start_date, datetime.now())).distinct('name', 'mobile')
        if not start_date and end_date:
            self._all = self._all = Customer.objects.filter(
                record__date_record__range=(Record.objects.order_by('date_record').first().date_record, end_date)). \
                distinct('name', 'mobile')
        return self._all

    def get_customer_count_by_date_range(self, start_date, end_date):
        return self.get_customer_by_date_range(start_date, end_date).count()


class ListCustomers(ListView):
    template_name = 'customers_list.html'
    queryset = Customer.objects.all()
    _record = None
    _customers = None

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any):
        self._customers = CustomerView()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # común para todas las clases list
        # context['url_create'] = reverse_lazy('project_create_root')
        # context['url_delete'] = reverse_lazy('project_delete_root')
        # espesíficos
        context['text_header'] = "Clientes"

        context['customers'] = self._customers.get_all()
        return context


class DetailCustomer(DetailView):
    template_name = 'customer_detail.html'
    model = Customer


class CreateCustomer(CreateView):
    template_name = ''
    model = Customer
    form_class = CustomerForm

    def post(self, request, *args, **kwargs):
        customer_form = CustomerForm(request.POST, request.FILES)
        if customer_form.is_valid():
            customer = customer_form.save()  # Crear una instancia de Customer pero no guardarla todavía
            serialized_customer = {
                'pk': customer.id,
                'name': customer.name,
                'mobile': customer.mobile,
                'photo': customer.get_photo(),
            }
            utility = customer.get_utility()
            utility_html = ''
            if utility:
                utility_html += '$ ' + str(utility)
            else:
                utility_html += '$ 0'
            get_debt_count = customer.get_debt_count()
            get_debt_count_html = ''
            if get_debt_count > 0:
                get_debt_count_html += '<span class="badge bg-danger" title="Este cliente posee deudas"> (' + str(
                    customer.get_debt_count()) + ') $' + str(customer.get_debt_amount()) + '</span>'
            count_customer_records = ''
            d = customer.record_set.count()
            if customer.record_set.count() > 0:
                count_customer_records += str(customer.record_set.count())
            else:
                count_customer_records += '0'

            new_customer_html = '<tr><td class="align-items-xxl-center"><span role="button">' \
                                '<img src="' + str(
                customer.get_photo()) + '"class="rounded-circle me-2 thumbnail" width="30" height="30" data-bs-toggle="modal" data-bs-target="#imagenModal" data-bss-tooltip="" ' \
                                        'data-img="' + str(
                customer.get_photo()) + '" alt="customer"> </span>' + customer.name + '</td>' \
                                                                                      '<td>' + str(
                count_customer_records) + '</td><td>' + str(utility_html) + str(get_debt_count_html) + '</td> ' \
                                                                                                       '<td>' + str(
                customer.date_join.strftime("%d de %B de %Y")) + '</td><td>' \
                                                                 '<button class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-bss-tooltip="" type="button" style="margin-right: 5px;" title="Permite editar los atributos de un cliente"><i class="fas fa-edit"></i></button> ' \
                                                                 '<a data-bs-toggle="tooltip" data-bss-tooltip="" class="btn btn-primary btn-sm" href="/app/customers/' + str(
                customer.pk) + '" style="margin-right: 5px;" title="Permite mostrar la información del cliente"><i class="fas fa-eye"></i></a> ' \
                               '<button class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-bss-tooltip="" type="button" title="Permite eliminar un cliente" style="margin-right: 5px;"><i class="far fa-trash-alt"></i></button></td></tr>'

            return JsonResponse(
                {'success': True, 'message': 'Cliente guardado correctamente', 'data': serialized_customer,
                 'new_customer_html': new_customer_html},
                safe=False,
                status=201)
        else:
            errors = json.loads(customer_form.errors.as_json())
            return JsonResponse({'success': False, 'errors': errors}, status=400)


class UpdateCustomer(UpdateView):
    template_name = 'customer/create.html'
    form_class = CustomerForm
    model = Customer
    success_url = reverse_lazy('customers')
    _customers = CustomerView()

    def dispatch(self, request, *args, **kwargs):
        self._customers = CustomerView()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.get_object()
        return context

    def form_valid(self, form):
        http = self.request.POST.get('url')
        self.success_url = http
        form = CustomerForm(self.request.POST, instance=self.object)
        if form.is_valid():
            form.save()
            messages.success(self.request, "Cliente editado correctamente")
            return super().form_valid(form)
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(self.request, f"Error en el campo {field}: {error}")
            return super().form_invalid(form)


class DeleteCustomer(DeleteView):
    model = Customer
    success_url = reverse_lazy("customers")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        data = {
            'message': 'Elemento eliminado exitosamente'
        }
        return JsonResponse(data)

templates/customer/create.html
{% extends 'layout/create.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'assets/select2/css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'assets/select2/css/select2.main.css' %}">

    <script src="{% static 'assets/sweetalert2/sweetalert2.js' %}"></script>
{% endblock %}
{% block container %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
                {% if message.tags == 'error' %}
                    <script>
                        Swal.fire({
                            position: "center",
                            icon: "error",
                            title: '{{message}}',
                            showConfirmButton: false,
                            timer: 2000
                        });
                    </script>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% endif %}
    <div id="modal-add-customer" class="modal fade" role="dialog" tabindex="-1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Nuevo cliente</h4>
                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex align-content-center justify-content-center">
        <div class="col-sm-12 col-lg-6 col-xl-4">
            <div class="card shadow">
                <div class="card-header flex-column justify-content-center align-items-center flex-wrap py-3">
                    <div class="">
                        <div>
                            <p class="text-primary d-flex justify-content-start align-items-center m-0 fw-bold">
                                Nuevo cliente</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form id="customer-form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label" for>
                                <strong>Nombre de cliente</strong>
                                <br/>
                            </label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3"><label class="form-label" for><strong>Teléfono (Opcional)</strong>
                            <br/>
                        </label>
                            {{ form.mobile }}
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for>
                                <strong>Foto (Opcional)</strong>
                                <br/>
                            </label>
                            {{ form.photo }}
                        </div>
                        <input type="hidden" id="url_back" name="url">
                        <span id="img-content"></span>
                        <div class="modal-footer">
                            <button id="btn-close-modal-add-customer" class="btn btn-light" data-bs-toggle="tooltip"
                                    data-bss-tooltip=""
                                    type="button" data-bs-dismiss="modal" title="Cancelar el guardado"><i
                                    class="fas fa-window-close"></i></button>
                            <button class="btn btn-primary" title="Permite guardar un cliente" type="submit">
                                <i class="fas fa-save"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'assets/js/forms_and_validations.js' %}"></script>
    <script src="{% static 'assets/select2/js/select2.js' %}"></script>
    <script src="{% static 'assets/select2/js/select2.js' %}"></script>
    <script>
        $("#single-select-field").select2({
            theme: "bootstrap-5",
            placeholder: $(this).data('placeholder'),
        });
        $("#record-form > div:nth-child(2) > div > div > div > span").attr('style', 'width:100%;');

        $('#url_back').val(document.referrer)

        $('#errorMessages').hide()
        $('#record-form').on('submit', function (event) {
            if (!validate_add_record_form()) {
                event.preventDefault();
            }
        });
        $('#id_photo').addClass('')

    </script>
    <script>
        $('#preview').remove()
        let url_image = ''
        {% if customer.photo %}
            url_image = "{{ customer.photo.url }}";
        {% endif %}
        $('#img-content').append('<img id="preview" src="' + url_image + '" src="#" alt="Visualización de imagen del cliente" width="100%" height="100%">')
    </script>
{% endblock %}